-- Oracle Table Definitions

-- OPERATOR - Used to store opertor setting and options
DROP TABLE OPERATOR;
CREATE TABLE OPERATOR
(
    ID          NUMBER(10),
    USERNAME    VARCHAR2(40),
    PASSWORD    VARCHAR2(40),
    CLIENT		NUMBER(10),    
    DTCREATED   DATE NOT NULL,
    DTMODIFIED  DATE NOT NULL,
    ROWVER      NUMBER NOT NULL
);
DROP SEQUENCE SQ_OPERATOR;
CREATE SEQUENCE SQ_OPERATOR START WITH 1000001 INCREMENT BY 1;

-- CLIENT - A client is an entity that owns accounts
DROP TABLE CLIENT;
CREATE TABLE CLIENT
(
    ID          NUMBER(10),
	FIRSTNAME	VARCHAR2(128),
	LASTNAME	VARCHAR2(128),
	EMAIL		VARCHAR2(128),
	BIRTHDAY	DATE,
	GENDER		NUMBER(3),
    DTCREATED   DATE NOT NULL,
    DTMODIFIED  DATE NOT NULL,
    ROWVER      NUMBER NOT NULL
);
DROP SEQUENCE SQ_CLIENT;
CREATE SEQUENCE SQ_CLIENT START WITH 1000001 INCREMENT BY 1;

-- ACCOUNT - An account belongs to a client and contains transactions
DROP TABLE ACCOUNT;
CREATE TABLE ACCOUNT
(
    ID				NUMBER(10), 
	CLIENT			NUMBER(10),
	ACCOUNTTYPE		NUMBER(3),
	BANKNUMBER		VARCHAR2(128),
	ACCOUNTNUMBER	VARCHAR2(128),
    DTCREATED		DATE NOT NULL,
    DTMODIFIED		DATE NOT NULL,
    ROWVER			NUMBER NOT NULL
);
DROP SEQUENCE SQ_ACCOUNT;
CREATE SEQUENCE SQ_ACCOUNT START WITH 1000001 INCREMENT BY 1;

-- Transaction - Belongs to an account
DROP TABLE TRANSACTION;
CREATE TABLE TRANSACTION
( 
    ID            NUMBER(10) NOT NULL,
	ACCOUNT		  NUMBER(10) NOT NULL,
    TYPE		  NUMBER(3) NOT NULL,
	DATEPOSTED	  DATE NOT NULL,
	AMOUNT		  NUMBER(19,4) NOT NULL,
	FITID		  VARCHAR2(128) NOT NULL,
	NAME		  VARCHAR2(128) NULL,
	MEMO		  VARCHAR2(128) NULL,
	CHECKNUM	  VARCHAR2(128) NULL,
    DTCREATED     DATE NOT NULL,
    DTMODIFIED    DATE NOT NULL,
    ROWVER		  NUMBER NOT NULL 
);
DROP SEQUENCE SQ_TRANSACTION;
CREATE SEQUENCE SQ_TRANSACTION START WITH 1000001 INCREMENT BY 1;


/*
-- XXX - Default table template
DROP TABLE XXX;
CREATE TABLE XXX
(
    ID          NUMBER(10),    
    DTCREATED   DATE NOT NULL,
    DTMODIFIED  DATE NOT NULL,
    ROWVER      NUMBER NOT NULL
);
DROP SEQUENCE SQ_XXX;
CREATE SEQUENCE SQ_XXX START WITH 1000001 INCREMENT BY 1;
*/