-- Oracle Table Definitions

DROP TABLE OPERATOR;

CREATE TABLE OPERATOR
(
  ID			NUMBER(10),
  USERNAME		VARCHAR2(40),
  PASSWORD		VARCHAR2(40),
  NAME			VARCHAR2(40),
  EMAIL			VARCHAR2(40),
  BIRTHDAY		DATE,
  GENDER		NUMBER(3),
  AGE			NUMBER(3),
  TEAMLEAD		NUMBER(3),
  DTCREATED		DATE NOT NULL,
  DTMODIFIED	DATE NOT NULL,
  ROWVER		NUMBER NOT NULL
);

CREATE SEQUENCE SQ_OPERATOR START WITH 1 INCREMENT BY 1;
