//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiskoFinanceCore.Resources {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class ErrorStrings {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal ErrorStrings() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiskoFinanceCore.Resources.ErrorStrings", typeof(ErrorStrings).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Account {0} not found.
		/// </summary>
		public static string errAccountNotFound {
			get {
				return ResourceManager.GetString("errAccountNotFound", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Account number is mandatory.
		/// </summary>
		public static string errAccountNumberMandatory {
			get {
				return ResourceManager.GetString("errAccountNumberMandatory", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Account type is mandatory.
		/// </summary>
		public static string errAccountTypeMandatory {
			get {
				return ResourceManager.GetString("errAccountTypeMandatory", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Bank name is mandatory.
		/// </summary>
		public static string errBankNameMandatory {
			get {
				return ResourceManager.GetString("errBankNameMandatory", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Category name cannot be blank.
		/// </summary>
		public static string errCategoryNameNull {
			get {
				return ResourceManager.GetString("errCategoryNameNull", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Category status is not set.
		/// </summary>
		public static string errCategoryStatusNull {
			get {
				return ResourceManager.GetString("errCategoryStatusNull", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Category type is not set.
		/// </summary>
		public static string errCategoryTypeNull {
			get {
				return ResourceManager.GetString("errCategoryTypeNull", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Must choose an existing account.
		/// </summary>
		public static string errChooseExistingAccount {
			get {
				return ResourceManager.GetString("errChooseExistingAccount", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Must choose only one existing account.
		/// </summary>
		public static string errChooseOnlyOneExistingAccount {
			get {
				return ResourceManager.GetString("errChooseOnlyOneExistingAccount", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Error!.
		/// </summary>
		public static string errError {
			get {
				return ResourceManager.GetString("errError", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Invalid account.
		/// </summary>
		public static string errInvalidAccount {
			get {
				return ResourceManager.GetString("errInvalidAccount", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Nickname is mandatory.
		/// </summary>
		public static string errNicknameMandatory {
			get {
				return ResourceManager.GetString("errNicknameMandatory", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No category selected to delete.
		/// </summary>
		public static string errNoCategorySelected {
			get {
				return ResourceManager.GetString("errNoCategorySelected", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No transactions found.
		/// </summary>
		public static string errNotTxnsFound {
			get {
				return ResourceManager.GetString("errNotTxnsFound", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Opening balance cannot be blank and must be a numerical value.
		/// </summary>
		public static string errOpeningBalance {
			get {
				return ResourceManager.GetString("errOpeningBalance", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Operator {0} not found.
		/// </summary>
		public static string errOperatorNotFound {
			get {
				return ResourceManager.GetString("errOperatorNotFound", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Operator not found. Cannot continue.
		/// </summary>
		public static string errOperatorNotFoundMustExit {
			get {
				return ResourceManager.GetString("errOperatorNotFoundMustExit", resourceCulture);
			}
		}
	}
}
