//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPFinanceCore.Resources {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Strings {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Strings() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MPFinanceCore.Resources.Strings", typeof(Strings).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Checking for duplicate transactions. Please wait....
		/// </summary>
		public static string strCheckingForDuplicateTxns {
			get {
				return ResourceManager.GetString("strCheckingForDuplicateTxns", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Choose an account to add the transactions to.
		/// </summary>
		public static string strChooseAnAccount {
			get {
				return ResourceManager.GetString("strChooseAnAccount", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Choose transactions to add.
		/// </summary>
		public static string strChooseTxnsToAdd {
			get {
				return ResourceManager.GetString("strChooseTxnsToAdd", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Please confirm?.
		/// </summary>
		public static string strConfirm {
			get {
				return ResourceManager.GetString("strConfirm", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Error!.
		/// </summary>
		public static string strError {
			get {
				return ResourceManager.GetString("strError", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Information.
		/// </summary>
		public static string strInfo {
			get {
				return ResourceManager.GetString("strInfo", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No transactions found for given search criteria.
		/// </summary>
		public static string strNoTxnsFound {
			get {
				return ResourceManager.GetString("strNoTxnsFound", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Page {0} / {1}.
		/// </summary>
		public static string strPageCounts {
			get {
				return ResourceManager.GetString("strPageCounts", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Showing {0} of {1} transactions.
		/// </summary>
		public static string strTransactionCounts {
			get {
				return ResourceManager.GetString("strTransactionCounts", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Warning!.
		/// </summary>
		public static string strWarning {
			get {
				return ResourceManager.GetString("strWarning", resourceCulture);
			}
		}
	}
}
